# These are supported funding model platforms

github: [yidasanqian]
patreon: yidasanqian
tidelift: maven/io.github.yidasanqian
custom: ['https://github.com/yidasanqian/yidasanqian.github.io/blob/master/images/alipay.jpg?raw=true', 'https://github.com/yidasanqian/yidasanqian.github.io/blob/master/images/wechat.jpg?raw=true']
